function [fitresult, gof] = createFit(Field, P_X, howSmooth, doPlot,name)
%CREATEFIT(FIELD_579,PD10PERX_579)
%  Create a fit.
%
%  Data for 'SS_0_579_1' fit:
%      X Input : Field_579
%      Y Output: PD10PerX_579
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Dec-2014 00:59:18


%% Fit: 'SS_0_579_1'.
[xData, yData] = prepareCurveData( Field, P_X );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = howSmooth;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


if doPlot
    % Create a figure for the plots.
    figure( 'Name', name );
    
    % Plot fit with data.
    subplot( 3, 1, 1 );
    h = plot( fitresult, xData, yData );
    legend( h, 'Torque vs. Field', 'SS', 'Location', 'NorthEast' );
    xlim([0,18])
    % Label axes
    xlabel Field
    ylabel Torque
    grid off
    
    % Plot residuals.
    subplot( 3, 1, 2 );
    h = plot( fitresult, xData, yData, 'residuals' );
    legend( h, 'SS - residuals', 'Zero Line', 'Location', 'NorthEast' );
    xlim([0,18])
    % Label axes
    xlabel Field
    ylabel Torque
    
    
    subplot( 3, 1, 3 );
    h = plot( fitresult, xData, yData );
    legend( h, 'Torque vs. Field', 'SS', 'Location', 'NorthEast' );
    % Label axes
    xlabel Field
    ylabel Torque
    grid off
    % Plot 2nd Derivative 
    %figure();
    subplot( 3, 1, 3 );
    h = plot(fitresult,'deriv2');
    %legend( h, 'Second Derivative of SS', 'Location', 'NorthEast' );
    % Label axes
    xlim([0,18])
    xlabel Field
    ylabel D2Torque
    grid off
end

end

